### ISSUE TITLE
Unhandled Exception: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by chrisb2244** [JamesMc86/G-CLI#100]
Probably something stupid that I've messed up, but I've recently gotten this error and had my builds crash a couple of times.
I haven't changed much, but I have changed some small things on the build machine (hence concern it's me...).

However, the builds will often succeed too, and if I "Replay" the build, then it worked each time so far.
On the most recent (just before I wrote this), the scripts were successfully executed 4/6 times for various LabVIEW bitness and debug/release builds, and then it errored on the 2nd to last set.

The Jenkins log reads:
Unhandled Exception: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.Sockets.Socket.Bind(EndPoint localEP)
at System.Net.Sockets.TcpListener.Start(Int32 backlog)
at G_CLI.lvComms..ctor()
at G_CLI.Program.Main(String[] args)
scons: building terminated because of errors.
scons: *** [Path\To\My\PPL.lvlibp] Error 3762504530

Error 3762504530 is undefined in LabVIEW.

Any thoughts on what might be going wrong?

**Comment by JamesMc86** [comment]
Wierd - it obviously can't be a real access restriction if it works most of the time.

The software attempts to find a free port to use - my guess is this could be a race condition where that port gets used in the time that we select it to making the connection (since we don't reserve it in any way). Do you have parallel builds going on? That might make that scenario more likely.

The new cross platform version I've been working on (but been pulled away from at the minute) lets the OS pick a free port by requesting port 0. If the .net API supports it that would be the solution here too

**Comment by chrisb2244** [comment]
I don't have parallel builds, but this is part of a series of builds in which LabVIEW is called with some arguments via G-CLI, and then when that finishes it is called again with a different set of arguments.

I would have to check logs for the exact pair of settings that can cause problems, but in the past I've seen issues (I think between repeated calls to the same LabVIEW version) where the connection times out. My Jenkins script handles this by just ignoring the first error and retrying, which then succeeds (I guess a race condition with closing and relaunching, not sure...).

Is it possible that the port is reported as free by .NET but is in some half-closed state with the previous call to G-CLI+LabVIEW?
If so, is there some reason this would be more likely now? (I guess since I haven't changed G-CLI, this would be a Windows Update problem?).

**Comment by chrisb2244** [comment]
Hmm, slight variation but probably doesn't add much, noting it just in case...

Today all 6 builds succeeded for a given run (with one timeout and retry, which is probably about typical... I should look at this but plan to maybe use Docker in the future which should obviate this problem) but when checking the version numbers using an EXE (previously compiled, stored in artifacts of a separate pipeline and copied over) I got the same socket error as in the title.

I think the use of an EXE vs a VI probably doesn't make a huge difference, but I wanted to add that now I've seen this for both (I guess the EXE only loads the LabVIEW RTE, not the IDE?).

Several other builds succeeded without hitting this, so I'd put this at ~1/20 calls to G-CLI since I first saw it?

**Comment by McGeifer** [comment]
Running into the same issue more or less frequently. Sometime it's running perfectly fine for days and sometimes I have to restart my CI pipeline over and over again until I get lucky.

**Comment by JamesMc86** [comment]
Thanks for the updates - let me see if I can eliminate that race condition. That is the biggest suspect for me but I'm not certain either.

**Comment by chrisb2244** [comment]
A fuller log of perhaps a related condition, this with the exe called at the end of the build:
```
Target build is Windows_32_Release, checkCmd is g-cli --lv-ver 2019  GetPPLVersion_32.exe -- "C:\Users\christian-butcher\Jenkins\workspace\All_PPLs\PPLs\Windows\Release_32\Fanuc_NSProxy.lvlibp"
[Pipeline] powershell
powershell.exe : Read Error
At C:\Users\christian-butcher\Jenkins\workspace\All_PPLs@tmp\durable-b1b5d9e2\powershellWrapper.ps1:3 char:1
+ & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Comm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Read Error:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
: Read Message: Exception Found System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> 
System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at G_CLI.lvComms.<readMessageData>d__16.MoveNext()
Since the network stream will be out of sync the application will now exit.
```

This one, I guess, looks like what you described (trying to get a connection that might have just been closed from a previous operation)?

**Comment by JamesMc86** [comment]
That sounds a little different to me. That reads to me that the LabVIEW end closed the connection without the C# end expecting it. Either because it didn't recieve and exit or hadn't processed it before LabVIEW closed

**Comment by chrisb2244** [comment]
So I was trying to track this down a bit better after a few more failed builds and discovered a slightly faster test system for triggering - I guess next will be rebuilding the source code on my PC with debugging and try step through, but for a race condition I expect it's difficult. It seems to hit this far less frequently when I do the following rather than a real build, but it can be triggered by repeatedly calling this command and doesn't require a LabVIEW launch (adding a non-existent VI name gives a different normal error, but can also trigger by repeatedly calling this command line):

`g-cli --lv-ver 200`
`g-cli --lv-ver 200 "nonVI.vi"`

```
C:\Users\Christian\dummy>g-cli --lv-ver 200 --verbose "nonVI.vi"
G CLI Started - Verbose Mode
Version 2.3.0.6 64-Bit
G CLI Arguments: --lv-ver 200 --verbose nonVI.vi
Arguments passed to LabVIEW:
Current Version: 2017 SP1 f3, 32bit
Detected LabVIEW versions:
2017 SP1 f3, 32bit(C:\Program Files (x86)\National Instruments\LabVIEW 2017\)
2019 SP1 f3, 32bit(C:\Program Files (x86)\National Instruments\LabVIEW 2019\)
2020 f1, 32bit(C:\Program Files (x86)\National Instruments\LabVIEW 2020\)
LabVIEW version "200" not found!
Available LabVIEW versions are:
2017 SP1 f3, 32bit
2019 SP1 f3, 32bit
2020 f1, 32bit

C:\Users\Christian\dummy>g-cli --lv-ver 200 --verbose "nonVI.vi"

Unhandled Exception: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at G_CLI.lvComms..ctor()
   at G_CLI.Program.Main(String[] args)
```
   
```
C:\Users\Christian\dummy>g-cli --lv-ver 200
No launch VI supplied!

C:\Users\Christian\dummy>g-cli --lv-ver 200

Unhandled Exception: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at G_CLI.lvComms..ctor()
   at G_CLI.Program.Main(String[] args)
```

Do the changes to the service locator code make a difference here if I use 2.4.0 when the multiple instances ini key is not set?

**Comment by chrisb2244** [comment]
Re this question/point:

> The new cross platform version I've been working on (but been pulled away from at the minute) lets the OS pick a free port by requesting port 0. If the .net API supports it that would be the solution here too

the documentation [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcplistener.-ctor?view=net-5.0#System_Net_Sockets_TcpListener__ctor_System_Net_IPAddress_System_Int32_) lists a constructor (the same one you're using, that is) that accepts 0 to be assigned a port:

>  If you do not care which local port is used, you can specify 0 for the port number. In this case, the service provider will assign an available port number between 1024 and 65535. If you use this approach, you can discover what local network address and port number has been assigned by using the LocalEndpoint property.

The link is for .NET 5.0, but the documentation for .NET Framework 4.7 and .NET Core 3.1 have identical text (at least for that couple of paragraphs). 
This might or might not be relevant -  I saw you're planning on moving to Rust for cross-platform in the future anyway!

**Comment by JamesMc86** [comment]
Merged - thanks Chris!

Great to have it fixed in this version anyway - the Rust version is all about when I can actually get the time to finish it.

I'll book in some time in the next week to get this properly released.

**Comment by chrisb2244** [comment]
Hi James,

I'm back to working on a new build system and running into this again - I had a vague memory that there was an issue about it (go figure) and came here, found the issue, saw the milestone/version, and checked my command line, saw 2.4.0.4 and figured I was stupid and hadn't updated.

Unfortunately, I guess a 2.5 release never happened, looking at the releases page?

Is the Rust version suitable for use instead (the alpha listed)? Or should I build a copy of this from somewhere around May last year locally? Or do you plan on releasing another copy of the C# code version? (I see this issue, and then maybe #102 mentioning a pre-3.0 release, #104 seems like it indicates instead a plan to release the 3.0 version soon?)

**Comment by JamesMc86** [comment]
Hi Christian,

I've struggled to put much time into this but I have a couple of weeks now where this is top of my list.

If you want to try the alpha, I've been running it for several months at this stage - then please do. The only feature missing is killing LabVIEW on a ctrl C command.

By the end of next week (perhaps this week) I hope to have the beta which includes the Ctrl C support and some improved error handler

I don't know if you can grab the latest build from GitHub actions? If so that is much closer to the beta (but will still identify as alpha2)

James McNally
Wiresmith Technology
t: 01635 597171
________________________________
