### ISSUE TITLE
": No bytes at port" errors

### ISSUE THREAD

**Issue by jcopetre** [JamesMc86/G-CLI#105]
In my Jenkins workflows, these errors show up fairly regularly. Often, the task will execute partially as verified by multiple "Write Line" calls successfully reaching the terminal from which the task was launched but, without any additional obvious concurrent event, I get a "Read Error \n : No bytes at port..." which terminates the task.
![no_bytes](https://user-images.githubusercontent.com/7269671/127916989-8be0145c-7d2a-449e-9720-935580491820.png)

I can't replicate this error when running this manually through a command prompt. It apparently only occurs when I run the task on my Jenkins servers.

Currently using G CLI 2.3.0.7, LV 2020

**Comment by JamesMc86** [comment]
Thanks for the report - Do you see any indication that the LabVIEW process continues to run? Often this can be because LabVIEW has crashed on the server for some reason.

**Comment by jcopetre** [comment]
Hey James--sorry for the delay here. I don't believe LV continues to run here. My Jenkins job is set to retry the build should it fail or timeout and the reattempts occasionally work. This particular application appears to have several issues with it, one of which I'm currently working with NI to resolve--namely, the build fails occasionally when attempting to build manually; however, I do suspect these aren't directly related failures as in the case of this automated build it does appear that LabVIEW just never starts?

I've set LV to discard any autosaves hoping that would prevent LabVIEW from hanging on open as I was observing that on occasion, manually opening LV on these automation servers I would be presented with the recovery dialog. However, this particular "No bytes at port" still persists.  

Do you have any other troubleshooting steps I can take to see what's going on here?

**Comment by JamesMc86** [comment]
The most likely cause is that the VI isn't running to completion and closing the port. 

You could add additional message output to G-CLI or even just to a local file to try and establish how far it is getting. 

I would also try running with the UI. Even if it isn't the normal setup log in to the server and run the jenkins connection as the user. Then you can see the LabVIEW UI launch and see whats going on.  That is likely to give a lot more clues.

**Comment by jcopetre** [comment]
Some updates on my end here: the TLDR is I've upgraded to LV2020sp1 and this issue has almost entirely disappeared. For my case, it's reliable enough that having Jenkins retry failures gets me through my pipeline reliably and I'm now able to bring the g-cli timeout in (was previously no timeout) so that I can fail early. My concern for this issue is now extinguished so feel free to close as you desire.

Additional details if you're interested: 
My specific implementation here does in fact push messages to the command line--this was a significant part of why I selected g-cli for the cli of this tool set. In all cases, I never see the first message that I expect; I write "Clearing compiled object cache" immediately upon running that task then "Building <application name>" after that call returns. I almost never saw the first message. 

I had also previously attempted to monitor the task but was limited to manually issuing relevant commands in the cmd prompt. My team runs these jobs under the Windows system profile which makes monitoring the task in situ impossible. When I run this manually, I have no issues. I also have set LabVIEW to ignore autosaves and recovery attempts that regularly hang LabVIEW on open attempts. When the failure condition is observed, manually opening the relevant projects shows no hang on open, no issues at all in opening in LabVIEW.

**Comment by wattyjams** [comment]
I too am now seeing this with regularity after I changed my setup and have moved from a single huge jenkins file to one which is calling other scripts, classes and has the call to VI tester done through a Jenkins based global Pipeline library.
I'm thinking that moving the call into the pipeline library is massively increasing the time it's taking Jenkins to execute and call LV and the TCP functions causing a timeout,
I'm running 2020 SP1 with params:
g-cli --lv-ver %LV_VER%  --%BIT% --timeout 90000 --kill-timeout 15000  viTester  -- -xml 
I thought that these setting were huge timeouts, but maybe they're not big enough?

**Comment by JamesMc86** [comment]
I've release v3.0 now which rewrites this part and should give clearer errors. 

I'm going to close this issue as the specific error can't be thrown anymore and it has been idle for a while. If you can try 3.0 and let me know if there is still a problem we can hopefully deal with a more specific message!
