### ISSUE TITLE
Application is crashing when started with -unattended (LV2021)

### ISSUE THREAD

**Issue by McGeifer** [JamesMc86/G-CLI#117]
After updating to LabVIEW 2021 32-Bit I ran into a problem I've no encountered jet.

I have an single VI build into an application that is using the G-CLI. I'm using this command to run my application:

`g-cli --kill --verbose "{path to my .exe"} -- -b "{a path my application needs}"` so nothing special here.

When using LV2020 everything is fine but when using LV2021 the application crashes immediately with the following error:

![grafik](https://user-images.githubusercontent.com/10698116/152953807-7aa04927-d4c0-4f4a-95c8-0c6c11b3ff6e.png)

The log file is almost empty and useless to my knowledge. Even when disabling the entire content of the VI with a diagram disable structure it crashes the same way.

After trying a few things I came up with a temporary solution. When the G-CLI is starting my application it does it with the `-unattended` flag which normally is a good thing cause we don't want any dialogue windows when running an application in a CI pipeline. But this flag seems to be the cause of the crash. In my application I set this flag to true anyway so this is not a problem.

Is there a way to disable the flag for now so I can still run my pipeline until there is some kind of fix for this?

**Comment by JamesMc86** [comment]
Hi @McGeifer 

Thanks for reporting this. I was wondering whether we need an option to remove that flag and you seem to have confirmed it!

If you add the flag `--allowDialogs` to the G CLI portion this should remove the unattended flag. Let me know if that fixes the issue and we can try and put something together as a bug report to NI.

**Comment by McGeifer** [comment]
Hi!

`--allowDialogs` is working perfectly fine 👍
