### ISSUE TITLE
g-cli crashes if LabVIEW 2022 Q3 is installed

### ISSUE THREAD

**Issue by jimkring** [JamesMc86/G-CLI#128]
**Issue**

After installing LabVIEW 2022 32-bit, I get the following error when I try to run g-cli

![image](https://user-images.githubusercontent.com/381432/183756929-408fbd5f-c901-417a-a11a-34de0098ec1e.png)

I'm suspecting that this problem is due to some changes that NI to LabVIEW 2022, with respect to the version number and how it is stored in the registry.

**New LabVIEW Versioning Scheme with YY.Q (e.g. 22.3)**

NI started using the minor version of LabVIEW's version for the Quarter of the annual release -- no more "SP1" moving forward.

For example, LabVIEW 2022 Q3 has a version of "22.3" -- and if NI releases a fixes/patches to this (used to be f1, f2, etc.), they will have versions like "22.3.1" and "22.3.2".

**Windows Registry is always "YY.0"**

Where things get tricky is that the Windows registry keys for the installed LabVIEW versions will always have a zero for the minor version.

For example, LabVIEW 2022 Q3 (version "22.3") has a registry entry here:

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\National Instruments\LabVIEW\22.0

And, for LabVIEW 2023 there will likely be Q1 and Q3 releases having versions "23.1" and "23.3" respectively -- only one of these can be installed at a time, and will show up in the registry at the following location:

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\National Instruments\LabVIEW\23.0

I hope this is helpful. Please let me know if you have any questions or need help testing.

**Comment by JamesMc86** [comment]
Hi Jim,

Thanks for the issues and all the detail - that all makes sense and I should be able to tweak the detection for that new scheme.

**Comment by JamesMc86** [comment]
The 3.0 version actually handles this correctly (I thought it would still fail!)

So I'll close this off - beta due in the next 48 hours :)

**Comment by jimkring** [comment]
Great! I'll happily test it out for you.

**Comment by JamesMc86** [comment]
Hi Pete,

Yep it should be fixed. The version of the exe you have running is out of date for some reason though even though the package is right, weird!

Easiest fix would be to uninstall the package, also uninstall from add remove programs, then reinstall and hopefully it should get you up to date

James McNally
Director/Systems Engineer
Wiresmith Technology
t: 01635 597171
________________________________

**Comment by phorn-NI** [comment]
Ahhh, thanks.

I think I know what happened - I previously had LV 2020 installed on this VM along with g-cli and a bunch of other packages. I uninstalled everything through NI PM before updating, but didn't remove the g-cli exe in add/remove programs, and I guess when I then installed the latest g-cli it didn't update the exe...

Thanks for the help, its working now 👍

**Comment by JamesMc86** [comment]
Unfortunately as we distribute through VIPM it would need that feature. It actually will prompt you to update packages when you open VIPM but doesn't support it as a background process.

**Comment by RobustoSystems** [comment]
Today I experienced the exact same issue and fix that Pete reported above. The solution - 1) uninstalling G-CLI using the Windows Settings >> Apps >> Installed Apps page, 2) uninstalling the VI package via VIPM, 3) re-installing the VIPM package - worked perfectly.

Computer details:
Windows 11 64-bit
LabVIEW 2024 Q3 64-bit

Posting this comment essentially as an upvote to the solution described above.

Thanks,
Petru
