### ISSUE TITLE
Unhandled exception when running g-cli or labview-cli

### ISSUE THREAD

**Issue by peterfoers** [JamesMc86/G-CLI#131]
Please note, that I've posted this question on the NI forum before: [here](https://forums.ni.com/t5/LabVIEW/Unhandled-exception-running-g-cli/td-p/4270238)

I installed g-cli in a vm and when running any commands I get an error. It doesn't make a difference if I try to run a vi or just run the command without anything. I'm using Version 2.4.0.5

The error I see is:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'G_CLI.LvVersions' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at G_CLI.LvVersions._ScanRegistry(RegistryView regView)
   at G_CLI.LvVersions.Scan()
   at G_CLI.LvVersions..cctor()
   --- End of inner exception stack trace ---
   at G_CLI.LvVersions.get_CurrentVersion()
   at G_CLI.Program.Main(String[] args)
```

Previously, I had labview-cli installed, which gave me the same result. Installation went without errors both times. I'm running on Win10 x64 with LabVIEW 2022 x86

What might be causing this?

**Comment by JamesMc86** [comment]
This is a known issue due to the LabVIEW name change, see https://github.com/JamesMc86/G-CLI/issues/128

Best thing is to use the 3.0 beta from the releases page and I need to get that on VIPM!

**Comment by peterfoers** [comment]
Thanks for the quick reply! It works now.
