### ISSUE TITLE
TypeInitializationException with G CLI 2.4.0.5

### ISSUE THREAD

**Issue by negentropicdev** [JamesMc86/G-CLI#141]
![image](https://user-images.githubusercontent.com/59840835/224877624-6bb967a6-35cc-4052-8715-03bdf82f4b5a.png)

Not sure how to progress. I'm just trying to run a VI that outputs the arguments to a dialog to test a call. I'll start poking around the source code.

**Comment by negentropicdev** [comment]
I've tried with verbose flag to get additional info and nothing additional gets displayed before the exception stack.

**Comment by negentropicdev** [comment]
Looking at the registry, neither the WoW node or the non-WoW node have a CurrentVersion item so perhaps it's not finding any installed versions because of the registry filtering?

**Comment by negentropicdev** [comment]
Here's the hierarchy I have in regedit WoW node (all community edition installs), are the folders besides 20.0, 22.0, AddOns, and CurrentVersion causing an issue?

**Comment by negentropicdev** [comment]
(Helps if I paste the screenshot)
![image](https://user-images.githubusercontent.com/59840835/224881404-0a8eaf8c-8eef-4fe6-bec2-f772a7d7ed28.png)

**Comment by JamesMc86** [comment]
I explicitly exclude AddOns and CurrentVersion but not Common so that may be the issue.

I'm gonna be a pain and ask if you can try 3.0 which I've just finally pushed as a release! You can get it from https://github.com/JamesMc86/G-CLI/releases/tag/v3.0.0 and this part has been rewritten.

I suspect it may have the same issue as it also won't filter out common so it will probably need patching.

Probably better to match on a pattern of dd.d where d is a digit rather than filtering out others.

**Comment by negentropicdev** [comment]
Until NI changes their versioning scheme again ^_^ Probably want to test every group for the Path subelement you're looking for.

I'll give the 3.0 release a shot and report back

**Comment by negentropicdev** [comment]
The rust build (3.0) does successfully launch LabVIEW.

**Comment by negentropicdev** [comment]
However, the VI isn't run once opened. I've also tried making sure Run when Opened is set which didn't help.

**Comment by negentropicdev** [comment]
It seems to be related to 2020 not having the ability to remember the run when opened allow preference. I'll dig into that some more.

**Comment by negentropicdev** [comment]
Definitely looks like a LabVIEW limitation. If I put the VI in vi.lib then it runs on launch. Which ultimately would be the destination anyways so I think I'm good here.
