### ISSUE TITLE
Running built executable can't connect in start CLI

### ISSUE THREAD

**Issue by negentropicdev** [JamesMc86/G-CLI#144]
It looks like when g-cli launches a .exe it's hardcoded to listen on port 5000 however the Start CLI in LabVIEW is still using the labview global labview.ini or service locator to link up with the g-cli

**Comment by JamesMc86** [comment]
I'll take a look - that shouldn't be the case.

The only difference with an exe is that we can trust the CLI args in LabVIEW so it should bypass the service locator - not to say I haven't mucked something up!

**Comment by JamesMc86** [comment]
Yep I screwed up:

https://github.com/JamesMc86/G-CLI/blob/7fa4e0cf5e3ea0e52c492deada31fdbb15c88209/rust-proxy/src/comms.rs#L54

Probably an artifact from early testing I missed. I'll look to patch this to autodetect a free port.

It should still work with a single exe but will fail with multiple as in #143

**Comment by JamesMc86** [comment]
Oh but let me know if you think there is something else going on as well. A single EXE should work without issue and that is tested as part of the release process.

**Comment by JamesMc86** [comment]
Just pushed a fix for this which will be in v3.0.1. I'll probably try to get that out this week with just that fix but going to review if there is anything else.

**Comment by JamesMc86** [comment]
Just pushed v3.0.1 to VIPM which should fix this. You can get it now on the release pages if you cant wait!

**Comment by negentropicdev** [comment]
Thanks! We'll give it a shot. I suspect there may still be an issue because the LabVIEW side was still trying to use service locator and failing since there wasn't a service registered, since we weren't launching a VI directly.

**Comment by negentropicdev** [comment]
Tha LabVIEW side deciding on whether to use service locator or passed parameter is gated on LabVIEW's INI check for AllowMultipleInstances

**Comment by JamesMc86** [comment]
This is a code clarity issue. It considers an exe a multi-instance version and that is handled in that VI with a conditional disable structure

This could be named or structured more clearly.

**Comment by negentropicdev** [comment]
Okay cool I'll take a look again I definitely missed that, shame on me!

**Comment by negentropicdev** [comment]
Yep, amazing how blind I can be to a blatant CDS structure :-D

Thanks again for the fix! My coworker was super impressed with the turnaround ;)
