### ISSUE TITLE
Start-cli argument parsing off 1 index for port when running an LV exe 

### ISSUE THREAD

**Issue by andycorb** [JamesMc86/G-CLI#147]
![image](https://github.com/JamesMc86/G-CLI/assets/20097563/cf3aec84-798f-4aaa-a792-9d4bb619b5b5)
Above is the error shown in the front panel of the top-level vi of the exe. The exe is invoked via PowerShell using the command:
`g-cli "<path of exe>"`

The exe has one vi with cli-start and cli-stop subvi calls, The cli-start vi errors and is unable to open a TCP connection.
![image](https://github.com/JamesMc86/G-CLI/assets/20097563/0bde6014-737c-4c02-8ad4-b4e683241211)

App argument 2 is the port whereas the below VI is looking for the port in arg 1.
![image](https://github.com/JamesMc86/G-CLI/assets/20097563/97ba1b95-be0e-466e-bb56-bac378de1541)

**Comment by JamesMc86** [comment]
Thanks for the report - I'm taking a look into it but seems like it should be straightforward to replicate.

**Comment by keerthivarman-nageshwaran** [comment]
I faced the same issue in LabVIEW 2016 32-bit, exe invoked from cmd. On comparing the difference between the Build Specification of `Echo Test` with the spec I had, the following boolean was enabled in mine.

![image](https://github.com/JamesMc86/G-CLI/assets/100664779/4dbf5b23-acd6-41e3-82e6-93ce5eec98b5)

Disabling this fixed the issue.

P.S. The issue can be reproduced by enabling the above mention boolean in `Echo Test` Build Specification.

**Comment by andycorb** [comment]
I was using 2021 64-bit. Unchecking Pass all command line arguments to application fixed the issue for me as well. thanks
