### ISSUE TITLE
New Name for LabVIEW-CLI?

### ISSUE THREAD

**Issue by JamesMc86** [JamesMc86/G-CLI#59]
There is now a lot of confusion with NI LabVIEW-CLI. I think perhaps we should consider a new name. There were a few ideas on twitter - please comment below with other ideas.

They were:

"Command Line Interface for LabVIEW" or "CIFL"
"LabVIEW Automation Interface"

**Comment by JamesMc86** [comment]
Other obvious would be G-CLI.

I should say, at this point we should probably still use labview-cli as the command for compatibility but think about a longer term migration, probably supporting both

**Comment by joerghampel** [comment]
I still like CIFL (Command Line Interface for LabVIEW) best. But maybe, it doesn't convey the fact that it's not the LabVIEW native one but a separate product.

How about "Open-Source Command Line Interface for LabVIEW" or "osCIFL"?

**Comment by JamesMc86** [comment]
I think I'm going to go with G-CLI. 'G' has tended to be synonymous with independent LabVIEW ("OpenG", "GDevCon") so it seems appropriate (and keeps the command short!). Next steps:

* Update the launch and add a redirect for the old command.
* Update source project names.
* Update VIPM Name
* Prepare for tools network.
* Resubmit to tools network under new name

**Comment by JamesMc86** [comment]
Changed the code. New command which is g-cli with a batch file that means that labview-cli command still works. Only likely break will be that the VIPM file wont recognise the change of name as the same package.
