### ISSUE TITLE
LabVIEW CLI doesn't return after "--kill --timeout=<short time>"

### ISSUE THREAD

**Issue by chrisb2244** [JamesMc86/G-CLI#63]
Currently trying to track down a slightly more elusive behaviour with the CLI when not passing the --kill switch, but in the process found the following:

When calling an otherwise working command line, passing the parameters "--kill --timeout=<some short time>" results in the messages

    Client Connected
    <LabVIEW splash screen appears, loading messages indicate libraries needed or the VI to be run>
    Connection to LabVIEW timed out! (expected behaviour, timeout is too short to load the VI)
    <CLI hangs, seemingly indefinitely. LabVIEW is killed and cannot be found in Task Manager>

Sending an interrupt with Ctrl-C exits the CLI and returns the command prompt as expected.

Is there anything that can be done here, or should I just set a much longer timeout always? I see in the source [Program.cs, line 168-176](https://github.com/JamesMc86/LabVIEW-CLI/blob/1f3a01a9ed01c754a784525b8e0d7d03403ce0c5/C%20Sharp%20Source/LabVIEW%20CLI/Program.cs) --timeout is used both for connection and kill, might it be possible to decouple these? (is that even desirable?).

**Comment by chrisb2244** [comment]
For reference, the version is shown (checked with "-v") as "Version 2.0.0.2 64-Bit".
I was initially concerned this wasn't the newest, but I see that this probably means the "b2" release. The build numbers for 2.0.0 are .18 and .391, and I can successfully launch into a running LabVIEW process.

**Comment by JamesMc86** [comment]
Sounds like a bug to me.  I would expect the CLI to just exit if it has failed to make a connection. Probably something wrong with the hand-off to the monitoring thread

**Comment by JamesMc86** [comment]
Just seen this on my integration tests so I have an easy replication

**Comment by JamesMc86** [comment]
Think I have tracked this down. I was missing the EnableRaisingEvents flag on the process object. Not sure why it worked previously but most of my test scenarios show it working now. Think it is also related to threading.

I will put this through the tests and mark this closed once it goes through everything.
