### ISSUE TITLE
Different behaviour for 32 and 64 bit LabVIEW executables without "--kill"

### ISSUE THREAD

**Issue by chrisb2244** [JamesMc86/G-CLI#64]
I'm not convinced this is a problem with LabVIEW-CLI (G-CLI?) but posting here in case I missed something.

When running on a remote Jenkins server without the "--kill" flag, and no specified "--timeout=<x>" value, the behaviour of the 32-bit and 64-bit versions of LabVIEW is different for me.

More specifically, LabVIEW 32-bit appears to close each time it is not in use, whereas LabVIEW 64-bit remains a "Background Process" (Windows 10 Enterprise Task Manager) (To be clear, 32-bit also opens as a Background Process, but closes). Is there any reason in the CLI tool that could cause this?

This leads to an unsuccessful build on the second and subsequent attempts until the process is killed using Task Manager. The builds fail because the workspace cannot be deleted (seemingly LV64 is still holding something in that directory).

This can be worked around using the "--kill" switch, but that results in (for me, significantly) slower builds (because the process doesn't return for "timeout" ms after receiving the Exit Code 0 message).

I don't see any specific bitness handling beyond getting the LV Path from a quick scan of the source, so I expect this should be closed, but does anyone know of a likely cause for this behaviour?

**Comment by JamesMc86** [comment]
Hi Chris,

If you run it with the -v flag for verbose it will show whether the CLI tool is the one closing 32 bit or not. There should not be any difference in treatment, but there are some funny things in some of the API calls to Windows with 64 bit vs 32 bit so it could be down to the tool although without the --kill flag it should be down to the code you run to close it.

I'm just trying to get a test run here before I have to go and I'll let you know if there is anything to report.

**Comment by JamesMc86** [comment]
On my local system running a basic echo test in the dev environment both act the same (this is 2018).

Both environments open, run the code, then go idle with the VI open so I think there is something else going on as well. A good test would be to login and run the commands direct on the server so you see the GUI. Perhaps the code tries to close the IDE but there is a hidden dialog under 64 bit holding onto it?

**Comment by chrisb2244** [comment]
I've been rewriting the build system to use SCons rather than Make for the last week or so, but it at least looks like I'm about to get a complete set of Windows 32-bit Release version PPLs successfully built, so I'll get back to checking this with my code probably tomorrow, or at least this week.

It's good(?) to know that it's probably my code, although I'm clueless at the moment as to a possible cause. Hopefully the tests you suggested will at least point me in the right direction (or some direction).

When I initially was testing this, on my local machine (rather than via Jenkins and a remote server), I don't remember seeing any problem with 64-bit without --kill. I think it might somehow be a timing problem on the remote server, but I'll check it a few more times and try get something better than "I don't have a clue"...

**Comment by chrisb2244** [comment]
I still haven't found anything conclusive on this, but just wanted you to know I haven't forgotten about it. The Jenkins machine occasionally leaves LabVIEW running and that sometimes causes timeout when attempting to connect. 

I've now found it's not only the 64-bit that hangs around, so I guess I just didn't see any 32-bit version problems when I first posted.

I think for now I'll go back to using --kill, but as mentioned here and in #63, I then seem to always wait the full timeout after stopping before the kill is processed (whereas currently it mostly continues straight away, until it times out trying to connect and then Jenkins hangs until the Jenkins job's forced timeout kills the job).

**Comment by chrisb2244** [comment]
> Both environments open, run the code, then go idle with the VI open so I think there is something else going on as well. A good test would be to login and run the commands direct on the server so you see the GUI. Perhaps the code tries to close the IDE but there is a hidden dialog under 64 bit holding onto it?

Very strong suspicion that I've found this now. Seems likely that I failed to correctly scan all nested dependencies when I moved from Make to SCons, and the two versions (64,32) were trying to build against each other, depending on order of builds, when last cleaned, which files existed or didn't exist...

This also explains why some of my 32-bit builds started to have problems (since some 64-bit PPLs appeared and broke 32-bit builds).
