### ISSUE TITLE
Possible "Quiet" CLI option?

### ISSUE THREAD

**Issue by chrisb2244** [JamesMc86/G-CLI#65]
The application has several levels of output, and can be controlled by the `-v` or `--verbose` switch. 

Messages written inside LabVIEW using CLI.lvclass:Write String.vi use the OUTP case, which writes directly to Console (rather than using the Output class).

If `-v` is not passed, the CLI application still places `Client Connected` and `Received Exit Code <code>` on the output.

Would it be possible to add a "quiet" mode, in which only the LabVIEW-specified strings are output to the console?

I'll work out a pull request for this if it's desirable (or at least, if you don't hate the idea - I think it might make command-line-ifying LabVIEW executables and parsing their outputs a little easier).

**Comment by JamesMc86** [comment]
Hi Chris,

Good suggestion, your right, these aren't desirable in most cases. I would be tempted to also only show these in verbose mode unless anyone shouts about wanting these all the time.

**Comment by JamesMc86** [comment]
These messages have been changed to only appear in verbose mode rather than adding a quiet mode.
