### ISSUE TITLE
Unhandled exception after LabVIEW exits 

### ISSUE THREAD

**Issue by joerghampel** [JamesMc86/G-CLI#70]
When called from GitLab Runner on Win7 64bit, g-cli throws an exception after LabVIEW finishes and exits:

`$ g-cli --kill --timeout 30000 -v --lv-ver 2016 "%TOOLS_FOLDER%%LABVIEW_RAT_PATH%rat-buildr\rat-buildr.vi" -- "%CI_PROJECT_DIR%" "%CI_PROJECT_NAMESPACE%" HL`

```
Unhandled Exception: System.ComponentModel.Win32Exception: Only part of a ReadProcessMemory or WriteProcessMemory request was completed
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at G_CLI.LvLauncher.findLabVIEWProcessByPath(String path)
   at G_CLI.LvLauncher.Process_Exited(Object sender, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
ERROR: Job failed: exit status 3762504530
```

This call to another LabVIEW project works on the same build server:

`$ labview-cli --kill --timeout 30000 -v --lv-ver 2016 "%TOOLS_FOLDER%%LABVIEW_RAT_PATH%rat-buildr\rat-buildr.vi" -- "%CI_PROJECT_DIR%" "%CI_PROJECT_NAMESPACE%" LIB`

**Comment by JamesMc86** [comment]
Hmm. so a few ideas you might be able to help with:

This is the exact error we expect from running the 32 bit version on a 64 bit OS.

In a simple form, we can add some extra error handling around this case to avoid the crash but I would like to make sure there isn't an install issue as well.

Can you check:

* In both calls does it identify the G CLI version as 64-bit (i.e. Version 2.0.0.2 64-Bit)? I know you confirmed one with me on another thread.
* If you look at add remove programs does it report the name as G CLI 64-bit (as below)?
* Does this occur every time?

![image](https://user-images.githubusercontent.com/4404192/57619534-0b742180-757e-11e9-8d9d-a3a858f5224a.png)

If it looks like these are all right then perhaps it is another cause of that error that we can handle that error (which we should add anyway)

**Comment by joerghampel** [comment]
Yes, both are identified as "2.0.0.2 64-Bit".
Yes, G CLI 64-bit (version 2.0.0.0) is listed in add/remove programs.
No, LabVIEW CLI is not listed anymore in add/remove programs.
Yes, the few times I've tried (3 or 4) it occurred identically each time.

As far as I can tell, the only differences are the VI that is being executed and the duration of the execution - the one that fails is the one that takes longer...

**Comment by JamesMc86** [comment]
So the reports back show that what was happening was @joerghampel system was seeing the same LabVIEW process again for some reason.

New version works - just need to review and make sure we are happy with it as a permanent solution

**Comment by JamesMc86** [comment]
Hidden message about this which will only show in debug mode once that is implemented. That will work as permanent solution.
