### ISSUE TITLE
When Kill Switch Is Set - Timeout Is Used Out Of Context

### ISSUE THREAD

**Issue by JamesMc86** [JamesMc86/G-CLI#84]
Just noticed that the options.timeout determines the timeout for LabVIEW to exit before we kill the process.

However this is described as the connection timeout. Should probably have another flag or an optional parameter on --kill for how long it should wait

**Comment by Bhargavi-Gowri** [comment]
Hi James,

I see the below error very often, I think this is something that you have mentioned above.

![image](https://user-images.githubusercontent.com/40823784/73256170-78504a00-41e7-11ea-95b1-21ab522715de.png)

Could you please let me know how to solve this issue?

Thanks,
Bhargavi Gowri.
