### ISSUE TITLE
LabVIEW Timeout Errors

### ISSUE THREAD

**Issue by JamesMc86** [JamesMc86/G-CLI#85]
Hi James,

I see the below error very often, I think this is something that you have mentioned above.

![image](https://user-images.githubusercontent.com/40823784/73256170-78504a00-41e7-11ea-95b1-21ab522715de.png)

Could you please let me know how to solve this issue?

Thanks,
Bhargavi Gowri.

_Originally posted by @Bhargavi-Gowri in https://github.com/JamesMc86/G-CLI/issues/84#issuecomment-579181092_

**Comment by JamesMc86** [comment]
Hi Bhargavi,

I moved this to a new issue - if it isn't directly related to the thread please start a new one.

There are a variety of causes for this. The most common are:

- Check you can open and run LabVIEW without licensing or recovery dialogues.
- Check your code isn't broken if you open it on the CI machine.
- Run with the GUI (as we discussed in the other issue) and see if any dialogues appear - they shouldn't any more - but it is good to be certain.
- See how long your code takes to load from scratch on the CI machine - if it is large, complex or searching for dependencies it can take longer than the default timeout (1 minute)

You can also try increasing the timeout to check  if it is slow with the flag --timeout 300000 (for 5 minutes for example)

**Comment by Bhargavi-Gowri** [comment]
Hi @JamesMc86 ,

Thanks for the reply. I will try the above mentioned things and let you know how it goes.

Thanks,
Bhargavi Gowri.

**Comment by Bhargavi-Gowri** [comment]
Hi @JamesMc86 ,

I have checked that the code is not broken and doesn't take more than 30 seconds to open. Still I see the connection time out error sometimes.

Could you please elaborate more on the point -- "You can also try increasing the timeout to check if it is slow with the flag --timeout 300000 (for 5 minutes for example)". Is this something to be done by  adding any keys to LabVIEW.ini file?

Thanks,
Bhargavi Gowri.

**Comment by JamesMc86** [comment]
Hi @Bhargavi-Gowri ,

It is another parameter for g cli. So your command might look like

`g-cli --lv-ver 2016 --timeout 300000 C:\myvi.vi`
