### ISSUE TITLE
Update (overwrite) output on the command line 

### ISSUE THREAD

**Issue by joerghampel** [JamesMc86/G-CLI#89]
Instead of adding output to the command line, implement a way to update the output at a certain position. This would be handy to display progress (a percentage, for example).

See https://stackoverflow.com/questions/60221/how-to-animate-the-command-line for an example.

**Comment by JamesMc86** [comment]
I've been thinking about these types of displays myself. What I will say is what is in that post should just work (G CLI doesn't alter anything you sent it) so \b and \r should work (though I haven't tested it)

**Comment by joerghampel** [comment]
Yes, I just tested it and can confirm that it works.
