### ISSUE TITLE
Provide an installer for non-LabVIEW-installed PCs?

### ISSUE THREAD

**Issue by chrisb2244** [JamesMc86/G-CLI#93]
I *think* that to run executables built using G-CLI with the appropriate behaviour, we need the G-CLI application installed on the target PC (because running "myExecutable.exe -- arg1 arg2" doesn't initiate the G-CLI communication, unlike "g-cli myExecutable.exe -- arg1 arg2", which has the desired behaviour).

It'd be nice if the Releases page had an installer that provided the necessary parts of the G-CLI project to run compiled executables on computers that don't have/want VIPM/LabVIEW installed.

As a workaround, I think these files already exist on a computer with G-CLI installed under <vi.lib>/Wiresmith Technology/G CLI/Installation Support

**Comment by JamesMc86** [comment]
Yep that is the same installer so this is definitely possible going forward. I'll dig into my CI server and see if I still have the installer standalone to add to previous versions too.
