### ISSUE TITLE
Infinite loop in Options Parser API when param is empty 

### ISSUE THREAD

**Issue by OlivierJourdan** [JamesMc86/G-CLI#94]
The issue raised using the last version of the [CLI tool for Antidoc](https://gitlab.com/wovalab/open-source/cli-for-antidoc).

In this version, I added params to set commit information like sha-1, commit date, and Tag. The Tag param can be empty.

When Tag is empty, Option Set Class:Parse Arguments.vi goes to an infinite loop. It seems that only happened when the empty value param in the Arguments array is the last one.

**Comment by JamesMc86** [comment]
Thanks for reporting, I can take a look at this.

Can you provide an example of how it is called and the configuration so I can create a test to replicate this.

**Comment by OlivierJourdan** [comment]
Here it is (need to be renamed as .vi). --> [Infinite Loop Issue - LV2014.zip](https://github.com/JamesMc86/G-CLI/files/5801253/Infinite.Loop.Issue.-.LV2014.zip)

Let me know if I can be of any further help.

**Comment by JamesMc86** [comment]
Thanks Olivier,

I'm pretty sure I see the issue. I'll probably try and release an update in the next few weeks with a few different patches.

**Comment by McGeifer** [comment]
Ran into the same problem today. Is there already a more precise date when a patch can be expected?

**Comment by JamesMc86** [comment]
I hope to work on it today - not sure if I'll get through the whole release process but will see if I can. Otherwise next week sometime.
