### ISSUE TITLE
Add multiple LabVIEW instances support

### ISSUE THREAD

**Issue by Zieleslaw** [JamesMc86/G-CLI#96]
Across multiple issues in this repo I saw a problem with LabVIEW already running or with closing it - and `allowmultipleinstances=True` flag in labview.ini is a solution to all of them.
We're using G-CLI tool in our Gitlab Runner and once I set more than 1 concurrent runner, the services interrupted each other, because they used the same service name. Changes from my pull request solve this - each "newly run" LabVIEW instance receives it's own port via command lines arguments, just like multiple EXEs already did.

**Comment by JamesMc86** [comment]
Hi @Zieleslaw,

Thanks for looking at the project and your contribution. I need to understand a little more though as I'm not sure this aligns with the direction of the project.

Allow multiple instances does help of course and if you want multiple concurrent runners to run independently I can see the use in that.

However working with an already open LabVIEW also has benefits - most noticeably in reducing execution time. While it certainly was challenging the mechanisms for this are now working well so I'm reluctant to remove them.

I would like to support both cases - is there something in the existing case that prevented this from working? I thought it should work anyway.

I'll take a look at the PR as well.

**Comment by JamesMc86** [comment]
Looking at the PR I think I see what you mean. There is a possible race conditions if multiple instances try to run the same VI which falling back to the port number resolves. It looks like a good idea.

**Comment by Zieleslaw** [comment]
I check for `allowmultipleinstance` flag in labview.ini - if it is false or nonexistent, G-CLI works like before (and I agree - it executes faster without starting the whole LabVIEW instance). So it is up to LabVIEW's configuration whether new, or already open instance will be used.
Maybe we could add G-CLI flag to make it more clear (and then change the flag in labview.ini via C# code) - you are surely more aware of the use cases for this tool :).
